# Conda commands to update langchain_apps environment to run langflow training examples.
# This assumes the environment "langchain_apps" is already built. 

# STEPS: 
# 1) conda activate langchain_apps
# 2) conda env update -f conda_UPDATE_langchain_apps_env.yml

name: langchain_apps
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - langchain-core
  - langchain-community
  - langchain-openai
  - langsmith
  - langgraph
  - langgraph-sdk
  - notebook
  - wikipedia
  - pip
  - pip:
    - langgraph-checkpoint-sqlite
    - tavily-python
    - trustcall
    - langgraph-cli